spring.application.name=capstone
# Import dell' env.properties
spring.config.import=file:env.properties
# Configurazione del Server
server.port=${PORT}
# Configurazione del Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate
spring.jpa.hibernate.ddl-auto=update
# Configurazione Cloudinary
cloudinary.name=${CLOUDINARY_NAME}
cloudinary.apikey=${CLOUDINARY_API_KEY}
cloudinary.secret=${CLOUDINARY_SECRET}
# JWT secret
jwt.secret=${JWT_SECRET}
mailgun.domainName=${MAILGUN_DOMAIN_NAME}
mailgun.apiKey=${MAILGUN_API_KEY}